import type { ReactNode } from "react";
import { Shield } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
export { RouteWorkspace } from "./RouteWorkspace";
export { ReportsWorkspace } from "./ReportsWorkspace";
export { HelpNearbyWorkspace } from "./HelpNearbyWorkspace";
export { TripsWorkspace } from "./TripsWorkspace";
const navLinks = [["Home", "/home"], ["Plan route", "/plan"], ["Trips", "/trips"], ["Reports", "/reports"], ["Help nearby", "/help"], ["Privacy", "/privacy"], ["Profile", "/profile"]] as const;
export function ProductShell({ children }: { children: ReactNode }) { const path = useLocation().pathname; const { account } = useAuth(); return <div className="min-h-screen bg-[#f7f6f1] text-[#14231d]"><aside className="fixed inset-y-0 hidden w-64 border-r border-[#d8ddd7] bg-[#fffefb] p-6 md:block"><Link to="/home" className="mb-8 flex items-center gap-2.5 font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center bg-[#16756c] text-white">S</span><span className="font-serif text-lg">SaferPath</span></Link><nav className="space-y-1" aria-label="Primary navigation">{navLinks.map(([label, href]) => <Link key={href} to={href} className={`block px-3.5 py-2.5 text-xs font-medium ${path === href ? "bg-[#dcefe9] font-semibold text-[#075b53]" : "text-[#53615a] hover:bg-[#f0f2ed]"}`}>{label}</Link>)}</nav><div className="absolute bottom-6 pr-8"><div className="flex items-center gap-2 text-[11px] font-semibold text-[#16756c]"><Shield className="h-3.5 w-3.5" />Contextual pilot</div><p className="mt-1 text-[11px] leading-4 text-[#62706a]">Contextual evidence, never guarantees. Your choices remain yours.</p></div></aside><header className="sticky top-0 z-20 flex h-14 items-center justify-between border-b border-[#d8ddd7] bg-[#fffefb]/95 px-6 backdrop-blur md:ml-64"><Link to="/home" className="font-serif text-lg font-bold md:hidden">SaferPath</Link><span className="hidden text-xs text-[#62706a] sm:block">Mumbai pilot corridor</span><div className="flex items-center gap-4"><Link to="/profile" className="text-xs font-semibold text-[#53615a]">{account?.display_name || "My Account"}</Link><Link to="/privacy" className="border border-[#d8ddd7] px-2.5 py-1 text-[11px] text-[#62706a]">Privacy Center</Link></div></header><main className="mx-auto max-w-7xl p-5 pb-24 md:ml-64 md:p-8">{children}</main></div>; }
